# Dot-source this in every shell that builds:  . "C:\Users\This\Desktop\Android Project\AndroidClient\env.ps1"
$env:JAVA_HOME        = "C:\Program Files\Microsoft\jdk-17.0.20.101-hotspot"
$env:ANDROID_HOME     = "C:\Android\sdk"
$env:ANDROID_SDK_ROOT = "C:\Android\sdk"
$env:GRADLE_HOME      = "C:\Gradle\gradle-8.9"
$env:GIT_TERMINAL_PROMPT = "0"
$env:PATH = "$env:JAVA_HOME\bin;$env:GRADLE_HOME\bin;C:\Program Files\nodejs;C:\Program Files\Git\cmd;$env:ANDROID_HOME\platform-tools;$env:ANDROID_HOME\cmdline-tools\latest\bin;$env:PATH"
Write-Host "env ready: JDK=$env:JAVA_HOME | SDK=$env:ANDROID_HOME | GRADLE=$env:GRADLE_HOME"
